{% set name = "django-haystack" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e3ceed6b8000625da14d409eb4dac69894905e2ac8ac18f9bfdb59323ca02eab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2
    - packaging

about:
  home: http://haystacksearch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Modular search for Django'
  description: |
    Haystack provides modular search for Django. It features a unified,
    familiar API that allows you to plug in different search backends
    (such as Solr, Elasticsearch, Whoosh, Xapian, etc.) without having
    to modify your code.
  doc_url: http://haystacksearch.org/
  dev_url: https://github.com/django-haystack/django-haystack

extra:
  recipe-maintainers:
    - rxm7706
    - scopatz
