{% set name = "django-haystack" %}
{% set version = "3.1.0" %}
{% set sha256 = "91ba27169aa785dc611b69ded52f8013b5b630cec10a883d46b8c028c5e18e6f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - django >=1.11
    # pkg_resources is required, which lives in the setuptools package
    - setuptools

about:
  home: http://haystacksearch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modular search for Django
  description: |
    Haystack provides modular search for Django. It features a unified,
    familiar API that allows you to plug in different search backends
    (such as Solr, Elasticsearch, Whoosh, Xapian, etc.) without having
    to modify your code.
  doc_url: http://haystacksearch.org/
  dev_url: https://github.com/django-haystack/django-haystack

extra:
  recipe-maintainers:
    - scopatz
